import React, { useState, useEffect, useRef } from 'react';
import { ArticleData, FontType } from '../types';
import { addCommentToDb, getCommentsFromDb } from '../services/firebase';
import { generateArticleAudio } from '../services/parserService';

interface ArticleViewProps {
  data: ArticleData;
  loading: boolean;
  onSave?: (article: ArticleData) => void;
  isSaved?: boolean;
  isDarkMode?: boolean;
  font: FontType;
}

interface Comment {
  id: string;
  author: string;
  text: string;
  date: string;
}

const ArticleView: React.FC<ArticleViewProps> = ({ data, loading, onSave, isSaved, isDarkMode = false, font }) => {
  const [chunks, setChunks] = useState<string[]>([]);
  const [visibleChunks, setVisibleChunks] = useState(1);
  const [comments, setComments] = useState<Comment[]>([]);
  const [newComment, setNewComment] = useState('');
  const commentsRef = useRef<HTMLDivElement>(null);

  // Audio State
  const [audioState, setAudioState] = useState<'idle' | 'loading' | 'playing' | 'paused'>('idle');
  const [audioSrc, setAudioSrc] = useState<string | null>(null);
  const audioRef = useRef<HTMLAudioElement | null>(null);

  // Load comments from DB (replacing localStorage)
  useEffect(() => {
    const loadComments = async () => {
        if (data.id && data.id !== 'error') {
            // First check local for immediate render
            const savedLocal = localStorage.getItem(`comments-${data.id}`);
            if (savedLocal) setComments(JSON.parse(savedLocal));

            // Then fetch from DB
            const dbComments = await getCommentsFromDb(data.id);
            if (dbComments.length > 0) {
                // Map DB format to UI format if needed, currently they match roughly
                setComments(dbComments);
            }
        } else {
            setComments([]);
        }
    };
    loadComments();
    
    // Reset Audio on new article
    if (audioRef.current) {
        audioRef.current.pause();
        audioRef.current = null;
    }
    setAudioState('idle');
    setAudioSrc(null);

  }, [data.id]);

  // Split content into "Pages" (Chunks)
  useEffect(() => {
    if (data.content) {
      const rawChunks = data.content.split(/(?<=<\/(?:p|div|section|blockquote|h1|h2|h3|h4|details|table)>)/i);
      
      const organizedChunks: string[] = [];
      let currentChunk = "";
      
      rawChunks.forEach(part => {
        currentChunk += part;
        if (currentChunk.length > 2500) {
           organizedChunks.push(currentChunk);
           currentChunk = "";
        }
      });
      if (currentChunk) organizedChunks.push(currentChunk);
      
      setChunks(organizedChunks);
      setVisibleChunks(1);
    }
  }, [data.content]);

  const handlePostComment = async () => {
    if (!newComment.trim()) return;
    const commentObj = {
        author: 'You',
        text: newComment,
        date: new Date().toLocaleDateString()
    };

    // Optimistic Update
    const tempComment = { id: Date.now().toString(), ...commentObj };
    const updatedComments = [...comments, tempComment];
    setComments(updatedComments);
    setNewComment('');
    
    // Backup to local
    localStorage.setItem(`comments-${data.id}`, JSON.stringify(updatedComments));

    // Persist to DB
    if (data.id && data.id !== 'error') {
        await addCommentToDb(data.id, commentObj);
    }
  };

  const handleDownloadHtml = () => {
    const element = document.createElement("a");
    const file = new Blob([`
      <html>
        <head>
          <title>${data.title}</title>
          <style>
             body { font-family: 'Georgia', serif; max-width: 680px; margin: 40px auto; padding: 20px; line-height: 1.6; color: #242424; }
             img, iframe { max-width: 100%; height: auto; margin: 20px 0; }
             h1 { font-size: 42px; line-height: 1.2; margin-bottom: 20px; font-family: Helvetica, Arial, sans-serif; }
             mark { background-color: #cffafe; }
             details { margin-bottom: 10px; border-bottom: 1px solid #eee; padding: 10px 0; }
             summary { cursor: pointer; font-weight: bold; font-family: Helvetica, Arial, sans-serif; }
          </style>
        </head>
        <body>
          <h1>${data.title}</h1>
          ${data.content}
          <div style="margin-top: 50px; font-size: 12px; color: #888;">Generated by MediumClone</div>
        </body>
      </html>
    `], {type: 'text/html'});
    element.href = URL.createObjectURL(file);
    element.download = `${data.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}.html`;
    document.body.appendChild(element); 
    element.click();
    document.body.removeChild(element);
  };

  const handleAudioToggle = async () => {
    // 1. If playing, pause
    if (audioState === 'playing') {
        audioRef.current?.pause();
        setAudioState('paused');
        return;
    }
    
    // 2. If paused, resume
    if (audioState === 'paused' && audioRef.current) {
        audioRef.current.play();
        setAudioState('playing');
        return;
    }

    // 3. If idle, generate audio
    if (audioState === 'idle') {
        setAudioState('loading');
        try {
            // Strip HTML to get clean text for TTS
            const tmpDiv = document.createElement("div");
            tmpDiv.innerHTML = data.content;
            const plainText = tmpDiv.textContent || "";
            
            // Generate audio using Puter.js (returns HTMLAudioElement)
            const audio = await generateArticleAudio(plainText);
            
            audioRef.current = audio;
            
            // Attach event listeners to manage state based on actual playback
            audio.onended = () => setAudioState('paused'); 
            audio.onpause = () => setAudioState('paused');
            audio.onplay = () => setAudioState('playing');
            audio.onerror = (e) => {
                console.error("Audio Playback Error", e);
                setAudioState('idle'); 
                alert("Audio format not supported by browser.");
            };

            await audio.play();
            // State update handled by onplay event above

        } catch (e) {
            console.error("Audio generation failed", e);
            setAudioState('idle');
            alert("Could not generate audio for this article. Please check your connection.");
        }
    }
  };

  const handleShare = () => {
      // Placeholder for future logic
      alert("Sharing functionality coming soon (requires login integration).");
  };

  const scrollToComments = () => {
    commentsRef.current?.scrollIntoView({ behavior: 'smooth' });
  };

  const getFontClass = () => {
      switch(font) {
          case 'sans': return 'font-sans';
          case 'system': return 'font-system';
          case 'dyslexic': return 'font-dyslexic';
          default: return 'font-serif';
      }
  };

  if (loading) {
    return (
      <div className="max-w-[680px] mx-auto mt-12 animate-pulse space-y-8">
        <div className={`h-12 rounded-sm w-3/4 ${isDarkMode ? 'bg-gray-800' : 'bg-gray-100'}`}></div>
        <div className="space-y-4">
            <div className={`h-4 rounded w-full ${isDarkMode ? 'bg-gray-800' : 'bg-gray-100'}`}></div>
            <div className={`h-4 rounded w-full ${isDarkMode ? 'bg-gray-800' : 'bg-gray-100'}`}></div>
            <div className={`h-4 rounded w-5/6 ${isDarkMode ? 'bg-gray-800' : 'bg-gray-100'}`}></div>
        </div>
      </div>
    );
  }

  if (!data.title && !data.content) {
    return (
      <div className={`max-w-[680px] mx-auto mt-24 text-center font-sans ${isDarkMode ? 'text-gray-400' : 'text-medium-gray'}`}>
        <h3 className={`text-xl mb-4 font-medium ${isDarkMode ? 'text-gray-200' : 'text-medium-black'}`}>Ready to read?</h3>
        <p>Paste a URL or upload a PDF above to convert it into a distraction-free Medium layout.</p>
        <p className="mt-2 text-sm text-gray-500">Try customizing highlights with the settings icon.</p>
      </div>
    );
  }

  const contentToRender = chunks.slice(0, visibleChunks).join('');
  const hasMore = visibleChunks < chunks.length;

  // Colors
  const textMain = isDarkMode ? 'text-medium-darkText' : 'text-medium-black';
  const textSecondary = isDarkMode ? 'text-medium-darkGray' : 'text-medium-gray';
  const borderCol = isDarkMode ? 'border-gray-800' : 'border-gray-100';

  return (
    <div className={isDarkMode ? 'bg-[#121212]' : 'bg-white'}>
      <style>{`
        @media print {
            nav, button, .no-print { display: none !important; }
            article { margin: 0 !important; padding: 0 !important; max-width: 100% !important; }
            body { background: white; color: black; }
            .print-only-visible { display: block !important; }
        }
        details > summary { list-style: none; }
        details > summary::-webkit-details-marker { display: none; }
        details[open] summary ~ * { animation: fadeIn 0.3s ease-in-out; }
        details[open] summary span { transform: rotate(45deg); }
        @keyframes fadeIn { 0% { opacity: 0; transform: translateY(-5px); } 100% { opacity: 1; transform: translateY(0); } }
      `}</style>

      <article className="max-w-[680px] mx-auto mt-12 mb-24 px-6 md:px-0">
        <header className="mb-10">
          <h1 className={`text-[42px] leading-[52px] font-bold ${getFontClass()} tracking-tight ${textMain} mb-6`}>
            {data.title}
          </h1>
          
          <div className="flex items-center justify-between mb-8 no-print border-b pb-8 border-gray-100 dark:border-gray-800">
              <div className="flex items-center space-x-3">
                  <div className="w-10 h-10 rounded-full bg-gray-200 overflow-hidden">
                      <img src="https://picsum.photos/100/100" alt="Author" className="w-full h-full object-cover" />
                  </div>
                  <div className="flex flex-col font-sans text-[14px]">
                      <div className="flex items-center space-x-2">
                          <span className={`font-medium ${textMain}`}>Reader Bot</span>
                          <span className="text-medium-green text-sm cursor-pointer">Follow</span>
                      </div>
                      <div className={textSecondary}>
                          <span>{data.readTime || '4 min read'}</span>
                          <span className="mx-1">·</span>
                          <span>{data.date || 'Just now'}</span>
                      </div>
                  </div>
              </div>
              
              {/* ACTION BAR: Play, Save, Share, Dots */}
              <div className="flex items-center space-x-6">
                 {/* 1. Play Audio (Moved First) */}
                 <button 
                   onClick={handleAudioToggle}
                   className={`hover:${textMain} transition-colors ${audioState === 'playing' ? 'text-medium-green' : 'text-gray-500'}`}
                   title="Listen"
                 >
                    {audioState === 'loading' ? (
                         <svg className="animate-spin h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                           <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                           <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                         </svg>
                    ) : audioState === 'playing' ? (
                        <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5"><rect x="6" y="4" width="4" height="16"></rect><rect x="14" y="4" width="4" height="16"></rect></svg>
                    ) : (
                        <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5"><polygon points="5 3 19 12 5 21 5 3"></polygon></svg>
                    )}
                 </button>

                 {/* 2. Bookmark/Save (Moved Under/After Audio) */}
                 {onSave && (
                    <button 
                      onClick={() => onSave(data)}
                      className={`hover:${textMain} transition-colors ${isSaved ? 'text-black dark:text-white' : 'text-gray-500'}`}
                      title="Save to Library"
                    >
                      <svg width="24" height="24" viewBox="0 0 24 24" fill={isSaved ? "currentColor" : "none"} stroke="currentColor" strokeWidth="1.5">
                        <path d="M19 21l-7-5-7 5V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2v16z"></path>
                      </svg>
                    </button>
                  )}

                 {/* 3. Share */}
                 <button 
                    onClick={handleShare}
                    className="text-gray-500 hover:text-black dark:hover:text-white transition-colors"
                    title="Share"
                 >
                    <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5"><path d="M4 12v8a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-8"></path><polyline points="16 6 12 2 8 6"></polyline><line x1="12" y1="2" x2="12" y2="15"></line></svg>
                 </button>

                 {/* 4. Dots */}
                 <button 
                    className="text-gray-500 hover:text-black dark:hover:text-white transition-colors"
                 >
                    <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5"><circle cx="12" cy="12" r="1"></circle><circle cx="19" cy="12" r="1"></circle><circle cx="5" cy="12" r="1"></circle></svg>
                 </button>
              </div>
          </div>

          {/* Medium-Style AI Summary */}
          {data.summary && (
            <div className={`my-10 ${getFontClass()} italic text-xl leading-relaxed ${textSecondary} border-l-[3px] ${isDarkMode ? 'border-gray-500' : 'border-medium-black'} pl-5`}>
              {data.summary}
            </div>
          )}

          <div className={`${borderCol} border-t border-b py-3 flex justify-between items-center ${textSecondary} text-sm font-sans mb-10 no-print`}>
              <div className="flex space-x-6 items-center">
                   <div className={`flex items-center space-x-2 cursor-pointer hover:${textMain}`} onClick={scrollToComments}>
                      <svg width="24" height="24" viewBox="0 0 24 24" fill="none"><path d="M21 11.5a8.38 8.38 0 0 1-.9 3.8 8.5 8.5 0 0 1-7.6 4.7 8.38 8.38 0 0 1-3.8-.9L3 21l1.9-5.7a8.38 8.38 0 0 1-.9-3.8 8.5 8.5 0 0 1 4.7-7.6 8.38 8.38 0 0 1 3.8-.9h.5a8.48 8.48 0 0 1 8 8v.5z" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"></path></svg>
                      <span>{comments.length}</span>
                   </div>
              </div>
              <div className="flex space-x-4">
                 {/* Bottom Actions if needed */}
              </div>
          </div>
        </header>

        <div 
          className={`
              ${getFontClass()} text-[20px] leading-[32px] ${textMain}
              [&>p]:mb-8 [&>p]:font-normal
              [&>h2]:text-2xl [&>h2]:font-bold [&>h2]:mt-10 [&>h2]:mb-4
              [&>p>mark]:bg-transparent
              [&>img]:w-full [&>img]:h-auto [&>img]:my-8 [&>img]:rounded-sm
              [&>iframe]:w-full [&>iframe]:rounded-sm [&>iframe]:my-8 [&>iframe]:aspect-video
          `}
          dangerouslySetInnerHTML={{ __html: contentToRender }} 
        />

        {/* Generate More Button */}
        {hasMore && (
          <div className="flex justify-center mt-12 mb-12 animate-in fade-in no-print">
             <button 
               onClick={() => setVisibleChunks(prev => prev + 1)}
               className={`group flex items-center gap-2 px-6 py-3 rounded-full border ${isDarkMode ? 'border-gray-700 bg-gray-800 hover:border-gray-500' : 'border-gray-200 bg-white hover:border-medium-black'} shadow-sm hover:shadow-md transition-all`}
             >
               <div className={`w-6 h-6 rounded-full bg-medium-green text-white flex items-center justify-center ${isDarkMode ? '' : 'group-hover:bg-black'} transition-colors`}>
                  <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="3"><line x1="12" y1="5" x2="12" y2="19"></line><line x1="5" y1="12" x2="19" y2="12"></line></svg>
               </div>
               <span className={`font-sans font-medium text-sm ${textMain}`}>Generate More</span>
             </button>
          </div>
        )}
        
        {/* Offline Download */}
        <div className="flex justify-center mb-10 no-print">
            <button 
                onClick={handleDownloadHtml}
                className={`text-gray-400 hover:text-medium-green text-sm font-sans flex items-center gap-2 underline`}
            >
                <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"></path><polyline points="7 10 12 15 17 10"></polyline><line x1="12" y1="15" x2="12" y2="3"></line></svg>
                Download Offline Copy (HTML)
            </button>
        </div>
        
        {/* Comments Section */}
        <div ref={commentsRef} className={`mt-10 border-t ${borderCol} pt-10 no-print`}>
            <h3 className="font-sans font-bold text-lg mb-6">Responses ({comments.length})</h3>
            
            <div className={`rounded shadow-sm border ${isDarkMode ? 'bg-gray-800 border-gray-700' : 'bg-white border-gray-100'} p-4 mb-8`}>
                <div className="flex items-center gap-3 mb-3">
                   <div className="w-8 h-8 rounded-full bg-gray-200 overflow-hidden">
                     <img src="https://picsum.photos/100/100" className="w-full h-full object-cover" />
                   </div>
                   <span className="text-sm font-sans font-medium">You</span>
                </div>
                <textarea 
                    value={newComment}
                    onChange={(e) => setNewComment(e.target.value)}
                    placeholder="What are your thoughts?"
                    className={`w-full resize-none outline-none ${getFontClass()} text-sm h-20 placeholder:font-sans placeholder:text-gray-400 bg-transparent ${textMain}`}
                />
                <div className="flex justify-end mt-2">
                    <button 
                        onClick={handlePostComment}
                        className={`px-4 py-1.5 rounded-full text-sm font-sans transition-colors ${newComment.trim() ? 'bg-medium-green text-white hover:bg-green-700' : 'bg-gray-100 text-gray-400 cursor-not-allowed dark:bg-gray-700 dark:text-gray-500'}`}
                        disabled={!newComment.trim()}
                    >
                        Respond
                    </button>
                </div>
            </div>

            <div className="space-y-8">
                {comments.map(comment => (
                    <div key={comment.id} className={`border-b ${isDarkMode ? 'border-gray-800' : 'border-gray-50'} pb-6 last:border-0`}>
                        <div className="flex items-center gap-3 mb-2">
                             <div className="w-8 h-8 rounded-full bg-gray-200">
                                <img src={`https://picsum.photos/seed/${comment.author}/100/100`} className="w-full h-full rounded-full" />
                             </div>
                             <div>
                                 <div className="text-sm font-sans font-medium">{comment.author}</div>
                                 <div className="text-xs text-gray-400 font-sans">{comment.date}</div>
                             </div>
                        </div>
                        <p className={`${getFontClass()} ${textMain} text-sm leading-relaxed`}>{comment.text}</p>
                    </div>
                ))}
            </div>
        </div>

      </article>
    </div>
  );
};

export default ArticleView;